#[env]
#TERM = "alacritty"

[general]
import = [
  "~/.config/alacritty/themes/themes/aura.toml",
]

[window]
padding.x = 10
padding.y = 10

# Only uncomment on MacOS
# option_as_alt = "Both"

opacity = 0.7
blur = true

[colors.primary]
background = "#000000"

[font]
normal.family = "Jetbrains Mono Nerd Font"
normal.style = "SemiBold"

# Only uncomment when need to disable italics
# italic.family = "Maple Mono"
# italic.style = "SemiBold"

size = 14
