#[env]
#TERM = "alacritty"

[window]
# padding.x = 10
# padding.y = 10

option_as_alt = "Both"

opacity = 0.8
blur = true

[colors.primary]
background = "#000000"

[font]
normal.family = "CaskaydiaCove Nerd Font"
normal.style = "Regular"

bold.family = "CaskaydiaCove Nerd Font"
bold.style = "SemiBold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "SemiBold"

offset.y = 4

size = 18
